# Generated by Django 4.0.5 on 2022-07-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('phone_number', models.CharField(max_length=10, unique=True, verbose_name='Номер телефона')),
                ('phone_operator', models.CharField(max_length=3, verbose_name='Мобильный оператор')),
                ('tag', models.CharField(max_length=25, verbose_name='Метка')),
                ('Timezone', models.DateTimeField(verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('date', models.DateTimeField(verbose_name='Дата начала рассылки')),
                ('messenge', models.CharField(max_length=255, verbose_name='Текст рассылки')),
                ('phone_operator', models.CharField(max_length=3, verbose_name='Мобильный оператор')),
                ('date_end', models.DateTimeField(verbose_name='Дата конца рассылки')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(verbose_name='Дата отправки сообщения')),
                ('status', models.CharField(max_length=25)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppModels.client')),
                ('id_forg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppModels.newsletter')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
