# Generated by Django 4.0.5 on 2022-07-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModels', '0002_alter_client_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id_forg',
            new_name='id_Newsletter',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='id_client',
            new_name='id_Сlient',
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(max_length=25, verbose_name='Статус'),
        ),
    ]
